#!/usr/bin/Rscript

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) {
  cat ("Usage: Rscript ALLcatchR_predict.R </full/path/to/input/quant_files> </full/path/to/output/directory> \n")
  cat ("\nOutput: Prediction_results.tsv in output directory\n")
  quit(status = 1)
}


quant <- args[1]
outdir <- args[2]
curdir <- getwd()

#install Libraries
suppressPackageStartupMessages({
  library(ALLCatchR) #can be removed since ALLcatchR2 available
  library(ALLCatchR2)
  library(ALLCatchRbcrabl1)
  library(tools)
})


file_list <- list.files(path = quant, 
                        pattern = "\\.tsv$", 
                        full.names = TRUE) # full.names=TRUE returns the full path

for (file_path in file_list) {
  samp_name <- file_path_sans_ext(basename(file_path))
  print(paste("Processing file:", samp_name))
  
  #Run ALLcatchR lineage (ALLcatchR2)
  out_file_name <- paste(outdir,"/",samp_name,"_lineage-prediction.tsv",sep="",collapse=NULL)
  allcatchr_lineage(Counts.file = file_path, ID_class = "ensembl_ID", sep = "\t", out.file = out_file_name)

  #Run ALLcatchR B-ALL (ALLcatchR)
  out_file_name <- paste(outdir,"/",samp_name,"_ball-prediction.tsv",sep="",collapse=NULL)
  out_plot_name <- paste(outdir,"/",samp_name,"_ball-prediction_plot",sep="",collapse=NULL)
  allcatchr_1.1(Lineage = "B-ALL", Counts.file = file_path, ID_class = "ensembl_ID", sep = "\t", out.file = out_file_name, plot.path = out_plot_name)
  
  
  #Run ALLcatchR BCR-ABL1 (ALLcatchR_bcrabl1)
  out_file_name <- paste(outdir,"/",samp_name,"_bcrabl1-prediction.tsv",sep="",collapse=NULL)
  allcatch_bcrabl1(Counts.file = file_path, ID_class = "ensemble_ID", sep = "\t", out.file = out_file_name)
  
  #Run ALLcatchR T-ALL (ALLcatchR2)
  out_file_name <- paste(outdir,"/",samp_name,"_tall-prediction.tsv",sep="",collapse=NULL)
  out_plot_name <- paste(outdir,"/",samp_name,"_tall-prediction_plot",sep="",collapse=NULL)
  allcatchr_1.1(Lineage = "T-ALL", Counts.file = file_path, ID_class = "ensembl_ID", sep = "\t", out.file = out_file_name, plot.path = out_plot_name)
}

#clean-up
removename <- paste(curdir,"/Rplots.pdf",sep="",collapse=NULL) #generated by allcatch_bcrabl1
file.remove(removename)